name: tnt_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  dots_indicator: ^3.0.0
  shared_preferences: ^2.4.0
  firebase_core: ^3.10.1
  dartz: ^0.10.1
  firebase_auth: ^5.4.1
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  modal_progress_hud_nsn: ^0.5.1
  google_sign_in: ^6.2.2


dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.0
  flutter_gen_runner: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_gen:
  assets:
    enabled: true
    output: lib/core/utils/app_images.dart
  fonts:
    enabled: true
flutter_intl:
  enabled: true
