// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmeylsdN80Zc9DWNoOyLHfrN9mrWYBFo',
    appId: '1:552334910122:web:1f88fcc0b04ea4d9b326d3',
    messagingSenderId: '552334910122',
    projectId: 'tnt-store-4ce51',
    authDomain: 'tnt-store-4ce51.firebaseapp.com',
    storageBucket: 'tnt-store-4ce51.firebasestorage.app',
    measurementId: 'G-MTXKF7RHC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdUl8wjSJgb9qYz0bV-QGjbBgvn_q0y8',
    appId: '1:552334910122:android:adb67b900a920d73b326d3',
    messagingSenderId: '552334910122',
    projectId: 'tnt-store-4ce51',
    storageBucket: 'tnt-store-4ce51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6-ZL5K0PeIvdLbjz5GvkL4DjtEG7524',
    appId: '1:552334910122:ios:0bacabaf2773bb75b326d3',
    messagingSenderId: '552334910122',
    projectId: 'tnt-store-4ce51',
    storageBucket: 'tnt-store-4ce51.firebasestorage.app',
    iosBundleId: 'com.example.tntStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6-ZL5K0PeIvdLbjz5GvkL4DjtEG7524',
    appId: '1:552334910122:ios:0bacabaf2773bb75b326d3',
    messagingSenderId: '552334910122',
    projectId: 'tnt-store-4ce51',
    storageBucket: 'tnt-store-4ce51.firebasestorage.app',
    iosBundleId: 'com.example.tntStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLmeylsdN80Zc9DWNoOyLHfrN9mrWYBFo',
    appId: '1:552334910122:web:2aa42a06c89dd981b326d3',
    messagingSenderId: '552334910122',
    projectId: 'tnt-store-4ce51',
    authDomain: 'tnt-store-4ce51.firebaseapp.com',
    storageBucket: 'tnt-store-4ce51.firebasestorage.app',
    measurementId: 'G-Q665SZP2XN',
  );
}
